### ISSUE TITLE
Json error on macOS 9

### ISSUE THREAD

**Issue by BjornB2** [smallsco/macstodon#10] opened 2024-04-16 07:27 UTC
Hi! 
While [waiting for the memory upgrade for my compact Mac](https://github.com/smallsco/macstodon/issues/9), I've installed macstodon on my iMac G3 / System 9.2.1
While installation works fine, I can't login to an instance. "Error parsing json response from server".

![URL](https://github.com/smallsco/macstodon/assets/3328086/35069c2c-02f0-49e9-b556-dc455a61bc60)

![error](https://github.com/smallsco/macstodon/assets/3328086/40624c1a-ce36-47c3-9a78-70d3a5cfdcaf)

![internet settings](https://github.com/smallsco/macstodon/assets/3328086/09af8bae-abfc-4608-a74e-ef472b6f1243)

I've tried before and after reinstalling macOS on this Mac.

Am I overlooking something obvious?

Thanks
Björn

**Comment by smallsco** [comment] 2024-04-16 13:32
Hi, `mastodon.social` is one of those servers that requires changes to your WebOne config file.

Under the `[Server]` section, please add the following (and comment out or remove any existing `UserAgent=` lines:
`UserAgent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15`

Under the `[ForceHTTPS]` section, please add `mastodon.social` on a line by itself.

After you have made these changes, you will need to restart WebOne, and then Macstodon should start to work for you!

**Comment by BjornB2** [comment] 2024-04-16 14:10
I already made those changes but I'll check them again when I get home. Thanks.

**Comment by BjornB2** [comment] 2024-04-16 15:23
Checked it but it doesn't seem to work. WebOne itself works but maybe it's not reading the config file correctly or something. I am running WebOne in a docker container and somehow can't get a terminal. I'll try another WebOne install later.

**Comment by smallsco** [comment] 2024-04-16 15:25
Can you pull up the WebOne log file? Does it show any connection attempts? What version are you running?

FWIW, I was only able to reproduce this issue without the changes to the WebOne config.

**Comment by BjornB2** [comment] 2024-04-16 15:27
```
16.04.2024 15:13:29.171+629071	>POST http://mastodon.social/api/v1/apps (172.17.0.1)
16.04.2024 15:13:29.171+1163240	 Unauthorized client.
16.04.2024 15:13:29.171+1185261	<Return code 407.
16.04.2024 15:13:29.171+1246936	<Done (connection close).
```

That's all I see. I do see http in stead of https though.

**Comment by smallsco** [comment] 2024-04-16 15:51
Interesting, the same request looks like this for me:

```
16.04.2024 06:28:55.061+10301	>POST http://mastodon.social/api/v1/apps (192.168.1.220)
16.04.2024 06:28:55.061+2390740	>Uploading 0K of application/x-www-form-urlencoded...
16.04.2024 06:28:55.061+10229479	 200 OK. Body 0K of application/json; charset=utf-8 [Text].
16.04.2024 06:28:55.061+10773505	<Done.
```

HTTP is correct in this case, don't worry about that.

The `Unauthorized client.` message makes me think that the User Agent is still not being sent correctly. Can you share your WebOne config file?

In `/etc/webone.conf.d/my.conf` I have the following:
```
[Server]
UserAgent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15

[ForceHttps]
oldbytes.space
botsin.space
bitbang.social
urusai.social
easymode.im
mastodon.social
```

Also, I am not running on Docker, but running on a Raspberry Pi.

**Comment by BjornB2** [comment] 2024-04-16 17:07
Ok consider me stupid. I had authentication enabled for WebOne. That's what it meant with Unauthorized client. 
For my browser I entered the credentials in the proxy settings. Forgot about it.
After disabling authentication (and closing the port to the outside) I get past the error. For now the mastodon website doesn't really want to load though but maybe I just have to wait a bit longer.

**Comment by smallsco** [comment] 2024-04-16 17:11
Glad you were able to get it working!

I've got the Mastodon auth page to load (for my instance) using the iCab browser on 68K, and with Classilla on PPC. But if that doesn't work for you, there is the option of typing the URL by hand on a modern machine, doing the authentication there, and then typing the response code back on the retro Mac.

**Comment by BjornB2** [comment] 2024-04-16 17:19
I did paste the URL in a .txt and copied it over using my appletalk share. Pasted the code back into it after logging in on my modern Mac. Works like a charm on my G3. Now let's see if my freshly arrived memory on my compact Mac also makes it work :)

**Comment by smallsco** [comment] 2024-04-16 17:21
Here's a cheat code if you don't want to go through the authentication dance again: copy the Macstodon Preferences file from your G3 to your compact Mac 😁

**Comment by BjornB2** [comment] 2024-04-16 17:22
haha awesome! will do :)

**Comment by smallsco** [comment] 2024-04-16 17:24
Closing this issue, let's keep #9 for anything that comes up with the compact Mac.

**Closed as completed by smallsco** 2024-04-16 17:24 UTC
