### ISSUE TITLE
Crash after auth code insertion

### ISSUE THREAD

**Issue by andreabusi** [smallsco/macstodon#6] opened 2023-02-22 20:10 UTC
Hi!
I'm trying to configure Macstodon on my iMac G3, but I'm stuck with an error just after the auth step.

This is my configuration:

- iMac G3 Rev A
- Mac OS 9.2.2 ITA
- Macstodon 0.4.3 (assigned memory: 16384 K)
- Webone configured on a Raspberry Pi and properly working (I can navigate properly from IE and Classilla)

I modified my Webone config to add these parameters:

```
[Server]
UserAgent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15

[ForceHttps]
mastodon.social
```

I'm able to perform the login on my Mastodon instance (mastodon.social) and retrieve the auth code. But when I put it on Macstodon, the app crashes with this stack trace:

```
Traceback (innermost last):
  File "SheepShaver:Desktop Folder:macstodon-src:Macstodon.py", line -12, in ?
  File "SheepShaver:Desktop Folder:macstodon-src:Macstodon.py", line 147, in __init__
  File "SheepShaver:Desktop Folder:macstodon-src:Macstodon.py", line 159, in mainloop
  File "SheepShaver:Python 1.5.2c1:Mac:Lib:FrameWork.py", line 178, in do1event
  File "SheepShaver:Python 1.5.2c1:Mac:Lib:FrameWork.py", line 207, in dispatch
  File "SheepShaver:Python 1.5.2c1:Mac:Lib:FrameWork.py", line 265, in do_mouseDown
  File "SheepShaver:Python 1.5.2c1:Mac:Lib:FrameWork.py", line 773, in do_inContent
  File "SheepShaver:Python 1.5.2c1:Mac:Tools:IDE:Wwindows.py", line 333, in do_contentclick
  File "SheepShaver:Python 1.5.2c1:Mac:Tools:IDE:Wcontrols.py", line 87, in click
  File "SheepShaver:Python 1.5.2c1:Mac:Tools:IDE:Wbase.py", line 682, in CallbackCall
  File "SheepShaver:Desktop Folder:macstodon-src:AuthHandler.py", line 128, in authTokenCallback
  File "SheepShaver:Desktop Folder:macstodon-src:MacstodonHelpers.py", line 173, in handleRequest
  File "SheepShaver:Python 1.5.2c1:Lib:urllib.py", line 636, in close
IOError: (0, 'Error')
```
Am I missing something? Thanks a lot in advance!

**Comment by smallsco** [comment] 2023-02-22 20:30
Hey,

Thanks for reporting and including the stack trace! Everything looks to be set up right - if WebOne wasn't working, you wouldn't get to the auth code screen in the first place.

I haven't run into this particular error before, but it looks like the remote end is closing the connection early (not sure if it's WebOne, or your instance doing that). However this is happening _after_ Macstodon has read the data from the server, so I think I can work around it by swallowing that particular exception if trying to close the connection fails.

I'll compile a test binary for you to try later today after I'm done with my workday 😀

**Comment by andreabusi** [comment] 2023-02-22 20:39
Wow, many thanks!

Can I perform some further tests in the meantime? I can try to register a new account on a different Mastodon instance. Any suggestion?

**Comment by smallsco** [comment] 2023-02-22 20:43
I've successfully used it with `oldbytes.space` and `urusai.social`. It's been reported to work on `bitbang.social` as well.

I went back through my mentions and found a report of it failing on `home.social` with the exact same error as you - so there's an interesting data point.

**Comment by smallsco** [comment] 2023-02-22 23:42
@andreabusi Please try the attached build (0.4.4-pre) and let me know if it works for you. If it does I'll publish a full release later tonight.
(Sorry for the crazy compression - GitHub won't let me attach a .sit.hqx file to an issue, so I had to zip it as well)

~Macstodon-PPC-0.4.4-pre.sit.hqx.zip~
use the version linked in the below comment instead

**Comment by smallsco** [comment] 2023-02-23 00:30
I made a silly typo.... please try the build attached to this post instead 😅

[Macstodon-PPC-0.4.4-pre.sit.hqx.zip](https://github.com/smallsco/macstodon/files/10809352/Macstodon-PPC-0.4.4-pre.sit.hqx.zip)

**Comment by andreabusi** [comment] 2023-02-23 05:37
Good news, it worked! I'm able to complete the login and see the home view! 🚀

I'm going to test the other functionality during the day, I will report here in case of any other issues.

**Comment by andreabusi** [comment] 2023-02-23 09:22
I found a new issue with Favorite/Boost buttons. They works properly, but the app return this error:

```
"The connection was closed by the remote server while Macstodon was reading data. Please check taht your SSL proxy is working properly."
```

If I check on Mastodon web, the action has been executed successfully:

![image](https://user-images.githubusercontent.com/847860/220866841-b935fd70-62c6-4da5-9056-f6c907512208.png)

On webone logs, I don't see any errors:

```
23.02.2023 09:17:26.431+563	>GET http://mastodon.social/api/v1/notifications?limit=5 (192.168.220.92)
23.02.2023 09:17:26.431+86202	>Downloading content...
23.02.2023 09:17:26.431+1304018	 200 OK. Body 0K of application/json; charset=utf-8 [Text].
23.02.2023 09:17:26.431+1355867	<Done.
23.02.2023 09:18:46.944+528	>POST http://mastodon.social/api/v1/statuses/109910138751300264/favourite (192.168.220.92)
23.02.2023 09:18:46.944+113094	>Downloading content...
23.02.2023 09:18:46.944+923800	 200 OK. Body 0K of application/json; charset=utf-8 [Text].
23.02.2023 09:18:46.944+931185	<Done.
```

**Comment by smallsco** [comment] 2023-02-23 14:35
Glad the first issue is fixed 😀

Regarding the second issue, there isn't really anything I can do about that. In this case, as the error message states, the remote end closed the HTTP connection _while_ Macstodon was reading the response from the server (as opposed to _after_ reading the response, which was the first issue). And because there was no response returned from the server, Macstodon doesn't know if the request worked or not.

We can't just ignore the lack of response like with the first issue - what if it occurred when, say, the timeline was being refreshed? We wouldn't be able to load new posts into the timeline because we wouldn't have the new posts returned from the server.

So unfortunately, until we can identify the root cause, whether it's something related to WebOne or to your instance (or even something related to a particular MacOS version or your hardware itself) - that's as far as I can provide support.

**Comment by andreabusi** [comment] 2023-02-23 15:08
It completely make sense to me, I know that is not an easy issue to look into.

I'm going to check if there is some WebOne configuration that I can adjust.

Anyway, if you need some tests or something else, don't hesitate to ask!

**Comment by smallsco** [comment] 2023-02-23 15:14
By all means - if you have the time, give it a try with different instances and WebOne configurations (and hardware / OS versions / emulators, if you're able). It would be nice to eliminate some variables 😀

**Comment by smallsco** [comment] 2023-02-24 03:03
Closing this - v0.4.4 has been released which fixes the original issue, and the second issue isn't really something that can be fixed on the Macstodon side. But feel free to message me if you are able to gather any more information on the second issue in your tests.

**Closed as completed by smallsco** 2023-02-24 03:03 UTC

**Comment by andreabusi** [comment] 2023-02-28 21:42
Hey! Just a quick follow-up. I created a vm using qemu and performed some further tests.
Using Mac OS 9.2.1 and 9.2.2 (ENG) and the same WebOne installation, it works fine. Favourite and Boost feature are working properly.

I see the issue only one time, but I'm not able to reproduce it.

**Comment by smallsco** [comment] 2023-02-28 21:44
Thanks, that's good to know. At some point I'll have to try using different-language versions of MacOS and see if I can reproduce. Seems weird that would be the cause, though.
